import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { validateReviews } from '../src/golden/workflow.ts';

const base=process.env.REVIEWER_SMOKE_URL || 'http://127.0.0.1:4174/word-connect-pwa/reviewer/';
const url=new URL(base.endsWith('/')?base:`${base}/`); const port=Number(process.env.REVIEWER_SMOKE_PORT||url.port||4174); const errors=[];
function preview(){ if(process.env.REVIEWER_SMOKE_EXTERNAL_URL==='1')return; const vite=fileURLToPath(new URL('../node_modules/vite/bin/vite.js',import.meta.url)); const p=spawn(process.execPath,[vite,'preview','-c','vite.reviewer.config.ts','--host','127.0.0.1','--port',String(port),'--strictPort'],{stdio:['ignore','pipe','pipe'],detached:true,env:{...process.env}}); p.stdout.on('data',x=>process.stdout.write(x));p.stderr.on('data',x=>process.stderr.write(x));return p; }
async function ready(){const until=Date.now()+20000;while(Date.now()<until){try{const r=await fetch(url);if(r.ok&&(await r.text()).includes('Human Golden Reviewer'))return;}catch{}await new Promise(r=>setTimeout(r,200));}throw new Error(`Reviewer preview unavailable: ${url.href}`);}
function watch(page,label){page.on('console',m=>{if(m.type()==='error')errors.push(`${label} console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`${label} pageerror: ${e.message}`));page.on('requestfailed',r=>{const t=r.failure()?.errorText||'';if(!t.includes('ERR_INTERNET_DISCONNECTED'))errors.push(`${label} request: ${r.url()} ${t}`)});}
async function reset(page){await page.evaluate(async()=>{await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase('word-connect-human-reviewer-v1');r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);r.onblocked=()=>resolve();});for(const r of await navigator.serviceWorker.getRegistrations())await r.unregister();for(const k of await caches.keys())if(k.startsWith('golden-reviewer-'))await caches.delete(k);});}
let server,browser;
try{
 server=preview();await ready();browser=await chromium.launch({headless:true});const context=await browser.newContext({serviceWorkers:'allow',acceptDownloads:true});
 for(const [w,h] of [[390,844],[1280,900]]){const p=await context.newPage();watch(p,`${w}x${h}`);await p.setViewportSize({width:w,height:h});await p.goto(url.href,{waitUntil:'networkidle'});if(w===390){await reset(p);await p.goto(url.href,{waitUntil:'networkidle'});}await p.waitForSelector('.word');if(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))errors.push(`${w}x${h} horizontal overflow`);const body=await p.locator('body').innerText();if(/predictedClass|targetScore|bonusScore|\breasons\b|\bstrata\b|frequencySignals|commonnessSignals/i.test(body))errors.push(`${w}x${h} blind leakage in DOM text`);if(w===390){await p.locator('#reviewer').fill('fixture-reviewer');await p.getByRole('button',{name:'Save ID'}).click();await p.locator('[data-class="TARGET"]').click();await p.locator('#confidence').evaluate(el=>{el.value='0.8';el.dispatchEvent(new Event('input',{bubbles:true}));});await p.getByRole('button',{name:'Save judgment'}).click();await p.waitForFunction(()=>document.body.innerText.includes('1 / 2000 reviewed'));await p.reload({waitUntil:'networkidle'});await p.waitForFunction(()=>document.body.innerText.includes('1 / 2000 reviewed'));
   const dl=await Promise.all([p.waitForEvent('download'),p.getByRole('button',{name:'Export my reviews'}).click()]).then(x=>x[0]);const path=await dl.path();if(!path)errors.push('export download path unavailable');else{const env=JSON.parse(readFileSync(path,'utf8'));if(env.schemaVersion!=='human-golden-reviews-v1'||env.reviews?.length!==1||env.reviews[0].reviewerId!=='fixture-reviewer')errors.push('browser export envelope invalid');const queue=JSON.parse(readFileSync('content/golden/human-golden-queue-esdb-en-us-v1.json','utf8'));if(validateReviews(queue,env.reviews).length)errors.push('browser export rejected by Golden validator');if(/predictedClass|targetScore|bonusScore|\breasons\b|\bstrata\b/i.test(JSON.stringify(env)))errors.push('export contains forbidden model metadata');}
 }
 await p.close();}
 const p=await context.newPage();watch(p,'offline');await p.goto(url.href,{waitUntil:'networkidle'});await p.waitForSelector('.word');const sw=await p.evaluate(async()=>{const r=await navigator.serviceWorker.ready;return{scope:r.scope,script:r.active?.scriptURL||r.waiting?.scriptURL||'',controlled:!!navigator.serviceWorker.controller};});if(!new URL(sw.scope).pathname.endsWith('/word-connect-pwa/reviewer/'))errors.push(`bad SW scope ${sw.scope}`);await p.reload({waitUntil:'networkidle'});if(!(await p.evaluate(()=>!!navigator.serviceWorker.controller)))errors.push('reviewer not SW-controlled after reload');const cdp=await context.newCDPSession(p);await cdp.send('Network.clearBrowserCache');await context.setOffline(true);await p.reload({waitUntil:'networkidle'});await p.waitForSelector('.word');if(!(await p.locator('body').innerText()).includes('1 / 2000 reviewed'))errors.push('offline reload lost local review state');await context.setOffline(false);await p.close();
}finally{await browser?.close();if(server?.pid){try{process.kill(-server.pid,'SIGTERM')}catch{}await new Promise(r=>setTimeout(r,200));try{process.kill(-server.pid,'SIGKILL')}catch{}}}
if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`Reviewer smoke passed at ${url.href}: 390x844 + 1280x900, blind UI, real-click synthetic fixture persistence/export, Golden validator compatibility, no horizontal overflow/errors, service worker scope/control, warm offline reload.`);
